<h1>Quiz</h1>

1. จงเขียน array ที่มีแต่เลข 0 แบบ vector 10 ตัว และ แบบ Matrix 4x4

In [2]:
import numpy as np
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
a = np.zeros((4,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2. จงเขียน array ที่มีแต่เลข 1 แบบ vector 5 ตัว และ แบบ Matrix 3x3

In [6]:
import numpy as np
b = np.ones(5)
print(b)

[1. 1. 1. 1. 1.]


In [7]:
b = np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3. จงเขียน array ที่มีเป็นการ random ตัวเลข 20 ตัว แบบ float ค่าอยู่ในช่วง 10-99 แล้วนำแต่ละเลขยกกำลังสอง

In [25]:
import numpy as np
c = np.random.uniform(10, 99, 20) ** 2
print(c)

[4340.99784253 4728.0145534  2966.28195061 3131.25794252 1724.95071951
 8987.61194496 2488.73369316 5401.70374617 4866.75783332 7892.45101374
 2978.11561549 1900.52644741 3229.98618506 1057.61839123  520.35790364
 1773.70834389 8910.99165286 4366.29497789 1081.58414472 7915.75090812]


4. ทำเหมือนข้อ 3 แต่เขียนแบบ List comprehension

In [23]:
import random
d = [random.uniform(10, 99)**2 for i in range(20)]
print(d)

[523.831478568823, 508.70737374642727, 3651.9353073934326, 232.74144325250677, 357.17823690896853, 3858.4969017544418, 1266.8861352693368, 3245.8346647414205, 2420.8372618915496, 7951.425570643124, 5371.192640546479, 2913.4869775626184, 976.5828031201465, 3951.8816073189705, 997.859510857466, 758.2646221279019, 3555.6153546292726, 1952.2082369627747, 3392.019407937572, 2000.9393220974796]


5. นำข้อ 3 และ 4 มาเปรียบเวลากัน โดยใช้ฟังก์ชั่น time.time( ) เพื่อจับเวลา แสดงผลลัพธ์ในรูปแบบมิลลิวินาที

In [52]:
import numpy as np
import random
import time
time1 = time.time()
c = np.random.uniform(10, 100, 20) ** 2
time2 = time.time()
d = [random.uniform(10, 99)**2 for i in range(20)]
time3 = time.time()
print(f'ข้อ 3 ใช้เวลา {time2-time1:.3f} มิลลิวินาที\nข้อ 4 ใช้เวลา {time3-time2:.3f} มิลลิวินาที')

ข้อ 3 ใช้เวลา 0.000 มิลลิวินาที
ข้อ 4 ใช้เวลา 0.004 มิลลิวินาที


6. จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลข 10 ถึง 1000

In [12]:
import numpy as np
x = np.arange(10,1001)
print(x)

[  10   11   12   13   14   15   16   17   18   19   20   21   22   23
   24   25   26   27   28   29   30   31   32   33   34   35   36   37
   38   39   40   41   42   43   44   45   46   47   48   49   50   51
   52   53   54   55   56   57   58   59   60   61   62   63   64   65
   66   67   68   69   70   71   72   73   74   75   76   77   78   79
   80   81   82   83   84   85   86   87   88   89   90   91   92   93
   94   95   96   97   98   99  100  101  102  103  104  105  106  107
  108  109  110  111  112  113  114  115  116  117  118  119  120  121
  122  123  124  125  126  127  128  129  130  131  132  133  134  135
  136  137  138  139  140  141  142  143  144  145  146  147  148  149
  150  151  152  153  154  155  156  157  158  159  160  161  162  163
  164  165  166  167  168  169  170  171  172  173  174  175  176  177
  178  179  180  181  182  183  184  185  186  187  188  189  190  191
  192  193  194  195  196  197  198  199  200  201  202  203  204  205
  206 

7. จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคู่ 10 ถึง 2000

In [14]:
import numpy as np
y = np.arange(10,2001,2)
print(y)

[  10   12   14   16   18   20   22   24   26   28   30   32   34   36
   38   40   42   44   46   48   50   52   54   56   58   60   62   64
   66   68   70   72   74   76   78   80   82   84   86   88   90   92
   94   96   98  100  102  104  106  108  110  112  114  116  118  120
  122  124  126  128  130  132  134  136  138  140  142  144  146  148
  150  152  154  156  158  160  162  164  166  168  170  172  174  176
  178  180  182  184  186  188  190  192  194  196  198  200  202  204
  206  208  210  212  214  216  218  220  222  224  226  228  230  232
  234  236  238  240  242  244  246  248  250  252  254  256  258  260
  262  264  266  268  270  272  274  276  278  280  282  284  286  288
  290  292  294  296  298  300  302  304  306  308  310  312  314  316
  318  320  322  324  326  328  330  332  334  336  338  340  342  344
  346  348  350  352  354  356  358  360  362  364  366  368  370  372
  374  376  378  380  382  384  386  388  390  392  394  396  398  400
  402 

8. จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคี่ 12 ถึง 900

In [1]:
import numpy as np
z = np.arange(12,901)
print(z[z%2==1])

[ 13  15  17  19  21  23  25  27  29  31  33  35  37  39  41  43  45  47
  49  51  53  55  57  59  61  63  65  67  69  71  73  75  77  79  81  83
  85  87  89  91  93  95  97  99 101 103 105 107 109 111 113 115 117 119
 121 123 125 127 129 131 133 135 137 139 141 143 145 147 149 151 153 155
 157 159 161 163 165 167 169 171 173 175 177 179 181 183 185 187 189 191
 193 195 197 199 201 203 205 207 209 211 213 215 217 219 221 223 225 227
 229 231 233 235 237 239 241 243 245 247 249 251 253 255 257 259 261 263
 265 267 269 271 273 275 277 279 281 283 285 287 289 291 293 295 297 299
 301 303 305 307 309 311 313 315 317 319 321 323 325 327 329 331 333 335
 337 339 341 343 345 347 349 351 353 355 357 359 361 363 365 367 369 371
 373 375 377 379 381 383 385 387 389 391 393 395 397 399 401 403 405 407
 409 411 413 415 417 419 421 423 425 427 429 431 433 435 437 439 441 443
 445 447 449 451 453 455 457 459 461 463 465 467 469 471 473 475 477 479
 481 483 485 487 489 491 493 495 497 499 501 503 50

9. จงสร้าง identity matrix แบบ 4x4

In [2]:
import numpy as np
x = np.eye(4,4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


10. จงหาว่า array ที่มีสมาชิก 100 ตัว เริ่มจาก 5 ถึง 25 มีผลต่างแต่ละตัวเท่ากับเท่าใด

In [3]:
import numpy as np
y = np.linspace(5,25,100)
print(y)

[ 5.          5.2020202   5.4040404   5.60606061  5.80808081  6.01010101
  6.21212121  6.41414141  6.61616162  6.81818182  7.02020202  7.22222222
  7.42424242  7.62626263  7.82828283  8.03030303  8.23232323  8.43434343
  8.63636364  8.83838384  9.04040404  9.24242424  9.44444444  9.64646465
  9.84848485 10.05050505 10.25252525 10.45454545 10.65656566 10.85858586
 11.06060606 11.26262626 11.46464646 11.66666667 11.86868687 12.07070707
 12.27272727 12.47474747 12.67676768 12.87878788 13.08080808 13.28282828
 13.48484848 13.68686869 13.88888889 14.09090909 14.29292929 14.49494949
 14.6969697  14.8989899  15.1010101  15.3030303  15.50505051 15.70707071
 15.90909091 16.11111111 16.31313131 16.51515152 16.71717172 16.91919192
 17.12121212 17.32323232 17.52525253 17.72727273 17.92929293 18.13131313
 18.33333333 18.53535354 18.73737374 18.93939394 19.14141414 19.34343434
 19.54545455 19.74747475 19.94949495 20.15151515 20.35353535 20.55555556
 20.75757576 20.95959596 21.16161616 21.36363636 21

11. จงเขียนฟังก์ชั่น random ตัวเลขแบบ float ในช่วง 0-1 ขึ้นมา 1 ตัว

In [4]:
import numpy as np
z = np.random.rand()
print(z)

0.7976906693805315


12. จงเขียนฟังก์ชั่นที่ random ตัวเลขแบบ int ในช่วง 50-100 โดยให้อยู่ในรูป Matrix 4x4 และ Transpose

In [10]:
import numpy as np
x = np.random.randint(50,101,(4,4))
print(x)

[[ 89  51  74  83]
 [ 80  59  70  61]
 [ 95 100  56  95]
 [ 84  58  56  82]]


In [11]:
print(x.T)

[[ 89  80  95  84]
 [ 51  59 100  58]
 [ 74  70  56  56]
 [ 83  61  95  82]]


13. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 8,9,13,14

In [1]:
import numpy as np
arr = np.array([[ 1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])

In [2]:
print(arr[1:3, 2:4])

[[ 8  9]
 [13 14]]


14. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 18,19,20

In [3]:
print(arr[3, 2:])

[18 19 20]


15. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 16,17,21,22

In [4]:
print(arr[3:, :2])

[[16 17]
 [21 22]]


16. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกทั้งแถว 3

In [5]:
print(arr[:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


17. จงเขียนโค้ดที่ทำให้ได้ array นี้ออกมา

In [12]:
import numpy as np
print(np.arange(1,26).reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


18. จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ If-else เช็คทีละตัวว่าตัวใดบ้างที่มีค่ามากกว่า 50 และปริ้นออกมา

In [11]:
import numpy as np
xlst = list()
x = np.random.randint(10,101,(5,5))
for i in range(5):
    for j in range(5):
        if (x[i][j] > 50):
            xlst.append(x[i,j])
print(f'Matrix 5x5\n{x}\n\nValue > 50\n{np.array(xlst)}')

Matrix 5x5
[[31 14 47 28 75]
 [83 42 20 65 25]
 [50 78 28 53 25]
 [19 95 62 63 59]
 [42 95 94 51 56]]

Value > 50
[75 83 65 78 53 95 62 63 59 95 94 51 56]


19. จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ conditional selection เช็คว่าตัวใดบ้างมีค่ามากกว่า 40 นำมาใส่ List ที่สร้างใหม่ และปริ้นออกมา

In [14]:
import numpy as np
y = np.random.randint(10,101,(5,5))
lst = y[y>40].tolist()
print(f'Matrix 5x5\n{y}\n\nValue > 40\n{lst}')

Matrix 5x5
[[37 50 35 81 98]
 [83 65 18 91 41]
 [77 75 33 35 93]
 [96 11 78 20 20]
 [45 14 17 99 63]]

Value > 40
[50, 81, 98, 83, 65, 91, 41, 77, 75, 93, 96, 78, 45, 99, 63]


20. เขียนโปรแกรมรับค่าจากผู้ใช้ให้ป้อนเลข 9 ตัว แต่ละตัวต้องไม่ซ้ำกันและมีค่าอยู่ในช่วง 10-100 นำเลข 9 ตัวนั้นมาทำเป็น matrix 3x3 และ transport และหาเลขอยู่ตำแหน่งที่ (2,2)

In [1]:
import numpy as np
num = list()
for i in range(9):
    while True:
        temp = int(input(f'กรุณาใส่เลขตัวที่ {i+1} ที่มีค่า 10-100 และไม่ซ้ำกัน: '))
        if (temp >= 10 and temp <= 100 and temp not in num):
            num.append(temp)
            break
print(f'''
Matrix 3x3
{np.array(num).reshape(3,3)}

Transport
{np.array(num).reshape(3,3).T}

Array (2,2)
{np.array(num).reshape(3,3).T[2,2]}''')

กรุณาใส่เลขตัวที่ 1 ที่มีค่า 10-100 และไม่ซ้ำกัน: 11
กรุณาใส่เลขตัวที่ 2 ที่มีค่า 10-100 และไม่ซ้ำกัน: 11
กรุณาใส่เลขตัวที่ 2 ที่มีค่า 10-100 และไม่ซ้ำกัน: 22
กรุณาใส่เลขตัวที่ 3 ที่มีค่า 10-100 และไม่ซ้ำกัน: 33
กรุณาใส่เลขตัวที่ 4 ที่มีค่า 10-100 และไม่ซ้ำกัน: 44
กรุณาใส่เลขตัวที่ 5 ที่มีค่า 10-100 และไม่ซ้ำกัน: 55
กรุณาใส่เลขตัวที่ 6 ที่มีค่า 10-100 และไม่ซ้ำกัน: 66
กรุณาใส่เลขตัวที่ 7 ที่มีค่า 10-100 และไม่ซ้ำกัน: 77
กรุณาใส่เลขตัวที่ 8 ที่มีค่า 10-100 และไม่ซ้ำกัน: 88
กรุณาใส่เลขตัวที่ 9 ที่มีค่า 10-100 และไม่ซ้ำกัน: 99

Matrix 3x3
[[11 22 33]
 [44 55 66]
 [77 88 99]]

Transport
[[11 44 77]
 [22 55 88]
 [33 66 99]]

Array (2,2)
99


---